/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.InterfaceObjekat;
import domen.Korisnik;
import domen.PDVStopa;
import domen.Porudzbenica;
import domen.StavkaPorudzbenice;
import domen.Sto;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import modelitabela.ModelTabeleStavki;
import transfer.ServerskiOdgovor;

/**
 *
 * @author User
 */
public class FKreirajPorudzbenicu extends javax.swing.JFrame {

    InterfaceObjekat korisnik;
    FGlavniMeni gf;
    FRadSaPorudzbenicama fp;
    boolean dodatjegrafik;
    Sto stoGrafik;
    int broj;
    Porudzbenica p;
    String statusRada;

    /**
     * Creates new form FKreirajPorudzbenicu
     */
    public FKreirajPorudzbenicu() {
        initComponents();
    }

    public FKreirajPorudzbenicu(InterfaceObjekat korisnik, FGlavniMeni gf) {
        initComponents();
        jtblstavke.setModel(new ModelTabeleStavki());
        this.korisnik = korisnik;
        this.gf = gf;
        dodatjegrafik = false;
        broj = 0;
        srediDatumiKorisnik();
        statusRada = "kreiraj";
        setLocationRelativeTo(null);

    }

    public FKreirajPorudzbenicu(InterfaceObjekat korisnik, FGlavniMeni gf, String status) {
        initComponents();
        jtblstavke.setModel(new ModelTabeleStavki());
        this.korisnik = korisnik;
        this.gf = gf;
        dodatjegrafik = false;
        broj = 0;

        jbtngrafik.setEnabled(false);
        srediDatumiKorisnik();
        statusRada = status;
        setLocationRelativeTo(null);
    }

    public FKreirajPorudzbenicu(InterfaceObjekat korisnik, Porudzbenica p) {
        initComponents();
        jtblstavke.setModel(new ModelTabeleStavki());
        this.korisnik = korisnik;
        dodatjegrafik = false;
        broj = 0;
        this.p = p;
        srediFormu(p);
        srediDatumiKorisnik();
        statusRada = "kreiraj";
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlabdatum = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtukupnasapdvom = new javax.swing.JTextField();
        jtxtukupnabezpdva = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jlabkorisnik = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblstavke = new javax.swing.JTable();
        jbtndodaj = new javax.swing.JButton();
        jbtnobrisi = new javax.swing.JButton();
        jbtnglavni = new javax.swing.JButton();
        jbtnnazad = new javax.swing.JButton();
        jbtnsacuvaj = new javax.swing.JButton();
        jbtngrafik = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kreiranje porudzbenice");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("Datum porudzbenice: ");

        jlabdatum.setText("jLabel2");

        jLabel2.setText("Ukupna cena (sa PDV-om):");

        jLabel3.setText("Ukupna cena ( bez PDV-a):");

        jtxtukupnasapdvom.setEnabled(false);

        jtxtukupnabezpdva.setEnabled(false);

        jLabel4.setText("Korisnik: ");

        jlabkorisnik.setText("jLabel5");

        jLabel5.setText("Sto:");

        jtblstavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jtblstavke);

        jbtndodaj.setText("Dodaj stavku porudzbenice");
        jbtndodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndodajActionPerformed(evt);
            }
        });

        jbtnobrisi.setText("Obrisi stavku porudzbenice");
        jbtnobrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnobrisiActionPerformed(evt);
            }
        });

        jbtnglavni.setText("Glavni meni");
        jbtnglavni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnglavniActionPerformed(evt);
            }
        });

        jbtnnazad.setBackground(new java.awt.Color(255, 102, 102));
        jbtnnazad.setText("Nazad");
        jbtnnazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnazadActionPerformed(evt);
            }
        });

        jbtnsacuvaj.setText("Sacuvaj");
        jbtnsacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsacuvajActionPerformed(evt);
            }
        });

        jbtngrafik.setText("Grafik sale");
        jbtngrafik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtngrafikActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cofee.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jbtnglavni)
                .addGap(26, 26, 26)
                .addComponent(jbtnnazad, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnsacuvaj)
                .addGap(98, 98, 98))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(132, 132, 132)
                                    .addComponent(jlabkorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(46, 46, 46)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jtxtukupnasapdvom, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlabdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtukupnabezpdva, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jbtngrafik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtndodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jbtnobrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlabkorisnik)
                                .addGap(6, 6, 6)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jlabdatum))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtukupnasapdvom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxtukupnabezpdva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jbtngrafik)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnobrisi)
                    .addComponent(jbtndodaj))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnglavni)
                    .addComponent(jbtnnazad)
                    .addComponent(jbtnsacuvaj))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnglavniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnglavniActionPerformed
        // TODO add your handling code here:
        gf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnglavniActionPerformed

    private void jbtnnazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnazadActionPerformed
        // TODO add your handling code here:
        this.dispose();
        if (fp != null) {
            fp.setVisible(true);
        }

    }//GEN-LAST:event_jbtnnazadActionPerformed

    private void jbtndodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndodajActionPerformed
        // TODO add your handling code here:
        FDodajStavku dsf = new FDodajStavku(this, true);
        dsf.pack();
        dsf.setVisible(true);
    }//GEN-LAST:event_jbtndodajActionPerformed

    private void jbtnobrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnobrisiActionPerformed
        // TODO add your handling code here:
        int red = jtblstavke.getSelectedRow();
        ModelTabeleStavki mts = (ModelTabeleStavki) jtblstavke.getModel();
        if (red != -1) {
            mts.obrisiStavku(red);
            srediUkupnoSaPdv();
            srediUkupnoBezPdva();
        } else {

            JOptionPane.showMessageDialog(this, "Niste odabrali stavku porudžbenice koju želite da obrišete");
            return;
        }
    }//GEN-LAST:event_jbtnobrisiActionPerformed

    private void jbtnsacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsacuvajActionPerformed
        // TODO add your handling code here:
        ModelTabeleStavki mts = (ModelTabeleStavki) jtblstavke.getModel();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        try {
            List<StavkaPorudzbenice> listaS = mts.getListaStavki();
            if (listaS.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Porudzbenica mora imati barem 1 stavku");
                return;
            }
            Date datum = sdf.parse(jlabdatum.getText());
            double ukupnopdv = Double.parseDouble(jtxtukupnasapdvom.getText());
            double ukupnobezpdv = Double.parseDouble(jtxtukupnabezpdva.getText());

            Sto sto = new Sto();

            if (dodatjegrafik == true) {
                sto = stoGrafik;
            } else {
                JOptionPane.showMessageDialog(this, "Niste obelezili sto na grafiku!");
                return;
            }

            if (sto.isStatus() == 1) {
                JOptionPane.showMessageDialog(this, "Izabrani sto je zauzet");
                return;
            }

            byte stat = 1;
            sto.setStatus(stat);
            ServerskiOdgovor so1 = Kontroler.getInstanca().izmeniSto(sto);

            if (so1.isUspesno()) {
                JOptionPane.showMessageDialog(this, "Zauzeli ste sto! ");
            } else {
                JOptionPane.showMessageDialog(this, "Ne mozete zauzeti ovaj sto");
            }
            Porudzbenica p = new Porudzbenica(-1, datum, ukupnopdv, ukupnobezpdv, (Sto) sto, (Korisnik) korisnik, listaS);

            ServerskiOdgovor so = Kontroler.getInstanca().sacuvajPorudzbenicu(p);

            if (so.isUspesno()) {
                ocistiFormu();
                JOptionPane.showMessageDialog(this, so.getPoruka());
            } else {
                JOptionPane.showMessageDialog(this, so.getPoruka());
            }
        } catch (ParseException ex) {
            Logger.getLogger(FKreirajPorudzbenicu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnsacuvajActionPerformed

    private void jbtngrafikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtngrafikActionPerformed
        // TODO add your handling code here:
        if (statusRada.equals("detalji")) {
            FIzaberiSto fs = new FIzaberiSto(this, true, true);
            fs.setVisible(true);
        }
        FIzaberiSto fs = new FIzaberiSto(this, true, broj);
        fs.pack();
        fs.setVisible(true);
    }//GEN-LAST:event_jbtngrafikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FKreirajPorudzbenicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FKreirajPorudzbenicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FKreirajPorudzbenicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FKreirajPorudzbenicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FKreirajPorudzbenicu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtndodaj;
    private javax.swing.JButton jbtnglavni;
    private javax.swing.JButton jbtngrafik;
    private javax.swing.JButton jbtnnazad;
    private javax.swing.JButton jbtnobrisi;
    private javax.swing.JButton jbtnsacuvaj;
    private javax.swing.JLabel jlabdatum;
    private javax.swing.JLabel jlabkorisnik;
    private javax.swing.JTable jtblstavke;
    private javax.swing.JTextField jtxtukupnabezpdva;
    private javax.swing.JTextField jtxtukupnasapdvom;
    // End of variables declaration//GEN-END:variables

    void srediZaUnos() {
        jbtnnazad.setVisible(false);
    }

    private void srediUkupnoSaPdv() {
        ModelTabeleStavki mts = (ModelTabeleStavki) jtblstavke.getModel();
        List<StavkaPorudzbenice> lista = mts.getListaStavki();
        double ukupnosapdvom = 0.00;

        for (StavkaPorudzbenice st : lista) {
            ukupnosapdvom += st.getUkupnaCenaSaPdvom();
        }

        jtxtukupnasapdvom.setText(ukupnosapdvom + "");
    }

    private void srediUkupnoBezPdva() {
        ModelTabeleStavki mts = (ModelTabeleStavki) jtblstavke.getModel();
        List<StavkaPorudzbenice> lista = mts.getListaStavki();
        double ukupnobezpdvom = 0.00;

        for (StavkaPorudzbenice st : lista) {
            ukupnobezpdvom += st.getUkupnaCenaBezPdva();
        }

        jtxtukupnabezpdva.setText(ukupnobezpdvom + "");
    }

    void dodajStavku(StavkaPorudzbenice sp) {
        ModelTabeleStavki mts = (ModelTabeleStavki) jtblstavke.getModel();
        List<StavkaPorudzbenice> lista = mts.getListaStavki();
        for (StavkaPorudzbenice stavka : lista) {
            if (sp.equals(stavka)) {
                mts.osveziKolicinu(stavka, sp.getKolicina());
                return;
            }
        }
        mts.dodajStavku(sp);
        srediUkupnoBezPdva();
        srediUkupnoSaPdv();

    }

    private void srediDatumiKorisnik() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        String datum = sdf.format(new Date());
        jlabdatum.setText(datum);
        Korisnik k = (Korisnik) korisnik;
        jlabkorisnik.setText(k.getIme() + " " + k.getPrezime());
    }

    private void ocistiFormu() {
        jtxtukupnasapdvom.setText("");
        jtxtukupnabezpdva.setText("");
        jtblstavke.setModel(new ModelTabeleStavki());
    }

    void srediFormuZaDetalje(Porudzbenica p) {
        ModelTabeleStavki mts = new ModelTabeleStavki();
        jbtndodaj.setVisible(false);
        jbtnobrisi.setVisible(false);
        jbtnsacuvaj.setVisible(false);
        jbtnglavni.setVisible(false);

        jtxtukupnasapdvom.setText(p.getUkupnaCenaSaPdvom() + "");
        jtxtukupnabezpdva.setText(p.getUkupnaCenaBezPdva() + "");
        List<StavkaPorudzbenice> lista = p.getStavkePorudzbenice();
        List<InterfaceObjekat> listaObj = new ArrayList<>();

        for (StavkaPorudzbenice io : lista) {
            listaObj.add(io);
        }
        mts.setListaStavki(listaObj);
        jtblstavke.setModel(mts);
    }

    void setForma(FRadSaPorudzbenicama aThis) {
        this.fp = aThis;
    }

    void setSto(Sto izabraniSto, int brojNovo) {
        stoGrafik = izabraniSto;
        dodatjegrafik = true;
        broj = brojNovo;
    }

    private void srediFormu(Porudzbenica p) {
        ModelTabeleStavki mts = new ModelTabeleStavki();
        SimpleDateFormat sf = new SimpleDateFormat("dd.MM.yyyy");
        jlabdatum.setText(sf.format(p.getDatumPorudzbenice()));
        jbtngrafik.setEnabled(true);

        jlabkorisnik.setText(p.getKorisnik().getIme() + " " + p.getKorisnik().getPrezime());
        jtxtukupnabezpdva.setText(Double.toString(p.getUkupnaCenaBezPdva()));
        jtxtukupnasapdvom.setText(Double.toString(p.getUkupnaCenaSaPdvom()));
        jbtnsacuvaj.setEnabled(false);

        List<StavkaPorudzbenice> lista = p.getStavkePorudzbenice();
        List<InterfaceObjekat> listaObj = new ArrayList<>();

        for (StavkaPorudzbenice io : lista) {
            listaObj.add(io);
        }
        mts.setListaStavki(listaObj);
        jtblstavke.setModel(mts);
    }

}
